In [5]:
value = "31 ['мужчина', 'убийство', 'дом', 'улица', 'девушка', 'житель', 'преступление', 'тело', 'квартира', 'нож']"
value[value.find("[")+1:-1]

"'мужчина', 'убийство', 'дом', 'улица', 'девушка', 'житель', 'преступление', 'тело', 'квартира', 'нож'"

In [13]:
import pandas as pd

d = {"1": [1, 2, 3, 4], "2": [1, 2, 3, 4], "3": [1, 2, 3, 4]}
pd.DataFrame(d.items(), columns=["theme", "keywords"])

  theme      keywords
0     1  [1, 2, 3, 4]
1     2  [1, 2, 3, 4]
2     3  [1, 2, 3, 4]

In [25]:
a = """
[8.10332636e-05 0.00000000e+00 0.00000000e+00 1.90816193e-03
 0.00000000e+00 0.00000000e+00 2.57569278e-02 0.00000000e+00
 2.24733372e-05 0.00000000e+00 9.28476891e-05 1.39687149e-02
 0.00000000e+00 0.00000000e+00 0.00000000e+00 1.18289308e-02
 0.00000000e+00 0.00000000e+00 4.49088928e-04 0.00000000e+00
 0.00000000e+00 0.00000000e+00 1.21852632e-03 0.00000000e+00
 1.94484964e-02 1.54258982e-02 0.00000000e+00 5.88987147e-04
 0.00000000e+00 0.00000000e+00 0.00000000e+00 3.64780658e-02
 1.84078908e-03 0.00000000e+00 2.13289578e-03 2.35716100e-03
 0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
 0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
 0.00000000e+00 1.56111291e-02 4.44753982e-04 1.02113293e-03
 0.00000000e+00 0.00000000e+00]
 """
a = a.replace(" ", ",").replace("\n", "")
eval(a)

([8.10332636e-05,
  0.0,
  0.0,
  0.00190816193,
  0.0,
  0.0,
  0.0257569278,
  0.0,
  2.24733372e-05,
  0.0,
  9.28476891e-05,
  0.0139687149,
  0.0,
  0.0,
  0.0,
  0.0118289308,
  0.0,
  0.0,
  0.000449088928,
  0.0,
  0.0,
  0.0,
  0.00121852632,
  0.0,
  0.0194484964,
  0.0154258982,
  0.0,
  0.000588987147,
  0.0,
  0.0,
  0.0,
  0.0364780658,
  0.00184078908,
  0.0,
  0.00213289578,
  0.002357161,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0156111291,
  0.000444753982,
  0.00102113293,
  0.0,
  0.0],)

In [31]:
a = """[8.10332636e-05\n\n\n 0.00000000e+00 0.00000000e+00 1.90816193e-03\n
 0.00000000e+00 0.00000000e+00 2.57569278e-02 0.00000000e+00
 2.24733372e-05 0.00000000e+00 9.28476891e-05 1.39687149e-02\n
 0.00000000e+00 0.00000000e+00 0.00000000e+00 1.18289308e-02
 0.00000000e+00 0.00000000e+00 4.49088928e-04 0.00000000e+00
 0.00000000e+00 0.00000000e+00 1.21852632e-03 0.00000000e+00
 1.94484964e-02 1.54258982e-02 0.00000000e+00 5.88987147e-04
 0.00000000e+00 0.00000000e+00 0.00000000e+00 3.64780658e-02
 1.84078908e-03 0.00000000e+00 2.13289578e-03 2.35716100e-03
 0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
 0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
 0.00000000e+00 1.56111291e-02 4.44753982e-04 1.02113293e-03
 0.00000000e+00 0.00000000e+00]"""
list(map(float, a[1:-1].split()))

[8.10332636e-05,
 0.0,
 0.0,
 0.00190816193,
 0.0,
 0.0,
 0.0257569278,
 0.0,
 2.24733372e-05,
 0.0,
 9.28476891e-05,
 0.0139687149,
 0.0,
 0.0,
 0.0,
 0.0118289308,
 0.0,
 0.0,
 0.000449088928,
 0.0,
 0.0,
 0.0,
 0.00121852632,
 0.0,
 0.0194484964,
 0.0154258982,
 0.0,
 0.000588987147,
 0.0,
 0.0,
 0.0,
 0.0364780658,
 0.00184078908,
 0.0,
 0.00213289578,
 0.002357161,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0156111291,
 0.000444753982,
 0.00102113293,
 0.0,
 0.0]

In [34]:
"keywords" in "keywords"

True